version: "3"

services:
  my_site:
    build:
      context: .
      dockerfile: etc/Dockerfile
    image: my_site:1.0.0
    container_name: my_site
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    sysctls:
      - net.core.somaxconn=100
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_HOST=mysql
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_volume:/var/lib/mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_DATABASE=my_site
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # nginx:
  #   restart: always
  #   container_name: nginx
  #   image: nginx:latest
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./etc/blog.conf:/etc/nginx/conf.d/blog.conf
  #   depends_on:
  #     - my_site

volumes:
  db_volume:
    driver: local
  redis_data:
    driver: local
