# Generated by Django 2.2.8 on 2019-12-13 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮件')),
                ('website', models.URLField(blank=True, verbose_name='个人网站')),
            ],
            options={
                'verbose_name_plural': '文章作者',
            },
        ),
        migrations.CreateModel(
            name='CarouselImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('name', models.CharField(max_length=50, verbose_name='图片名称')),
                ('description', models.CharField(max_length=100, verbose_name='图片描述')),
                ('path', models.CharField(max_length=100, verbose_name='图片地址')),
                ('link', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='图片外链')),
                ('weights', models.SmallIntegerField(blank=True, default=10, null=True, verbose_name='图片权重')),
                ('img_type', models.SmallIntegerField(choices=[(1, 'banner'), (2, 'ads')], default=1, verbose_name='类型')),
            ],
            options={
                'verbose_name_plural': '轮播管理',
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': '文章分类',
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='网站名称')),
                ('link', models.CharField(max_length=100, verbose_name='网站地址')),
                ('avatar', models.CharField(blank=True, default='', max_length=100, verbose_name='网站图标')),
                ('desc', models.CharField(blank=True, default='', max_length=200, verbose_name='网站描述')),
                ('weights', models.SmallIntegerField(blank=True, default=10, null=True, verbose_name='权重')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='联系邮箱')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '友情链接',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('name', models.CharField(max_length=50, verbose_name='音乐名称')),
                ('url', models.CharField(max_length=100, verbose_name='音乐地址')),
                ('cover', models.CharField(max_length=100, verbose_name='音乐封面')),
                ('artist', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='艺术家')),
                ('lrc', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='音乐歌词')),
            ],
            options={
                'verbose_name_plural': '背景音乐',
            },
        ),
        migrations.CreateModel(
            name='OwnerMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(blank=True, max_length=100, null=True, verbose_name='简介')),
                ('message', models.TextField(default='', verbose_name='寄语')),
                ('editor', models.SmallIntegerField(choices=[(1, '富文本编辑器'), (2, 'Markdown编辑器')], default=1, verbose_name='编辑器类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '主人寄语',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('email', models.EmailField(max_length=254, verbose_name='订阅邮箱')),
            ],
            options={
                'verbose_name_plural': '邮件订阅',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='标签名')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '文章标签',
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('nickname', models.CharField(max_length=50)),
                ('avatar', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('blogger', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '访客管理',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('content', models.TextField()),
                ('target', models.CharField(blank=True, max_length=100, null=True)),
                ('anchor', models.CharField(blank=True, max_length=20, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('province', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='article.Comments')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replyers', to='article.Visitor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Visitor')),
            ],
            options={
                'verbose_name_plural': '评论管理',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(default='', verbose_name='文章内容')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('count', models.IntegerField(default=0, verbose_name='文章点击数')),
                ('editor', models.SmallIntegerField(choices=[(1, '富文本编辑器'), (2, 'Markdown编辑器')], default=1, verbose_name='编辑器类型')),
                ('status', models.SmallIntegerField(choices=[(1, '草稿'), (2, '已发布')], default=2, verbose_name='状态')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Author', verbose_name='作者')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Classification', verbose_name='分类')),
                ('tags', models.ManyToManyField(blank=True, to='article.Tag', verbose_name='标签')),
            ],
            options={
                'verbose_name_plural': '博文管理',
                'ordering': ['-publish_time'],
            },
        ),
    ]
