# Generated by Django 3.0.3 on 2020-04-21 13:40

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_articlemanager_author_carouselimg_classification_comments_links_music_ownermessage_subscript'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-id'], 'verbose_name_plural': '博文管理'},
        ),
        migrations.AddField(
            model_name='article',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='最后修改时间'),
        ),
        migrations.AddField(
            model_name='author',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改时间'),
        ),
        migrations.AddField(
            model_name='classification',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classification',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改时间'),
        ),
        migrations.AddField(
            model_name='links',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改时间'),
        ),
        migrations.AddField(
            model_name='ownermessage',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='最后修改时间'),
        ),
        migrations.AddField(
            model_name='tag',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改时间'),
        ),
    ]
