# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-07 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0034_auto_20190507_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replyers', to='article.Visitor'),
        ),
    ]
