# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-07 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0035_comments_reply_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor',
            options={'verbose_name_plural': '\u8bbf\u5ba2\u7ba1\u7406'},
        ),
        migrations.AddField(
            model_name='comments',
            name='anchor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
