# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-08 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0035_comments_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='blogger',
            field=models.BooleanField(default=False),
        ),
    ]
