# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-23 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0036_visitor_blogger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': '\u8bc4\u8bba\u7ba1\u7406'},
        ),
    ]
