# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-08 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0036_auto_20190507_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='ip_address',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='province',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
